# Generated by Django 2.0.3 on 2019-03-30 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('face_image', models.ImageField(blank=True, null=True, unique=True, upload_to='accounts/faces/%Y-%m-%d/', verbose_name='Face Image')),
                ('face_encoding', models.BinaryField(null=True)),
            ],
        ),
    ]
