# Generated by Django 2.0.3 on 2018-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180313_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='request',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
