# Generated by Django 2.0.3 on 2019-02-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='posts/uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='sha1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
